import React from "react"
import { CheckParagraph } from "./CheckParagraph"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CheckParagraph,
  "https://www.figma.com/design/fy3i5KbWj9kjUuLk7gQGlo/Core-Components?node-id=507-2557&m=dev",
  {
    props: {},
    example: (props) => <CheckParagraph />,
  },
)
